[build]
  publish = "frontend/build"  # Frontend build dizini
  command = "npm run build --prefix frontend"  # Frontend'in build edilmesi için gereken komut

[[redirects]]
  from = "/api/*"   # Frontend'deki /api ile başlayan istekler
  to = "http://localhost:5000/api/:splat"  # Yerel backend'e yönlendirilecek (yerel testler için)
  status = 200
  force = true
