[build]
  command = "npm run build --prefix front"  # Frontend için build komutunu belirtin
  publish = "front/build"                   # Yayınlanacak dizin, build klasörü

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200
  force = true
