[build]
  base = "front"  # Frontend dizinine git
  command = "npm run build"  # build komutunu çalıştır
  publish = "build"  # Build edilmiş dosyaların yeri

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200
  force = true
